### PR TITLE
Fix #187 by storing univariate_id as int64

### LINKED ISSUE #187: Some univariate_id cannot be written to Delta Lake
Some `u64` `univariate_id`s cause errors when written to Delta Lake as it looks like they are stored as `Int64` instead of `UInt64` despite the field being defined as `Field::new("univariate_id", DataType::UInt64, false)`. For example `tag_one` and/or `tag_two` [previously](https://github.com/ModelarData/ModelarDB-RS/pull/185/commits/479068853db104db8cd14ac070c2dca9cb516afa) used in the integration tests causes the following error to occur when executing the tests: `Failed to flush data in compressed data manager due to: Failed to convert into Arrow schema: Cast error: Can't cast value 11069825858223412227 to type Int64`.

### PR DESCRIPTION
**Pull request by skejserjensen**
This PR fixes #187 by storing `univariate_id` as `Int64Array` instead of `UInt64Array` as the [Delta](https://github.com/delta-io/delta-rs/issues/2175) [Lake](https://github.com/delta-io/delta-rs/issues/1751) [Protocol](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#primitive-types) does not support unsigned integers and #197 probably will not be resolved for some time. When reviewing this PR, please double check the necessary casts are performed everywhere they are needed. Currently, `UInt64Array` is reinterpreted as `Int64Array` when writing compressed segments to disk and `Int64Array` is reinterpreted as `UInt64Array` when data points are reconstructed from segments and aggregates are computed directly from the segments.

### CODE REVIEW

File: crates/modelardb_common/src/storage.rs [hunk 1]
```diff
@@ -330,6 +335,34 @@ pub async fn extract_azure_blob_storage_arguments(
...
+    }
+}
+
+/// Reinterpret the bits used for univariate ids in `compressed_segments` to convert the column from
+/// [`Int64Array`] to [`UInt64Array`] as the Delta Lake Protocol does not support unsigned integers.
+pub fn univariate_ids_int64_to_uint64(compressed_segments: &RecordBatch) -> RecordBatch {
+    let mut columns = compressed_segments.columns().to_vec();
+    let signed_univariate_ids = crate::array!(compressed_segments, 0, Int64Array);
+    let univariate_ids: UInt64Array =
+        signed_univariate_ids.unary(|value| u64::from_ne_bytes(value.to_ne_bytes()));
```
Comment (chrthomsen) [inline crates/modelardb_common/src/storage.rs:359]: Same as above: is it safe to use native endianness? Do we risk to write with one endianness and then later read with another endianess (on the client)?

File: crates/modelardb_common/src/storage.rs [hunk 2]
```diff
@@ -330,6 +335,34 @@ pub async fn extract_azure_blob_storage_arguments(
...
 }
 
+/// Reinterpret the bits used for univariate ids in `compressed_segments` to convert the column from
+/// [`UInt64Array`] to [`Int64Array`] as the Delta Lake Protocol does not support unsigned integers.
+fn univariate_ids_uint64_to_int64(compressed_segments: &mut Vec<RecordBatch>) {
+    for record_batch in compressed_segments {
+        let mut columns = record_batch.columns().to_vec();
+        let univariate_ids = crate::array!(record_batch, 0, UInt64Array);
+        let signed_univariate_ids: Int64Array =
+            univariate_ids.unary(|value| i64::from_ne_bytes(value.to_ne_bytes()));
```
Comment (chrthomsen) [inline crates/modelardb_common/src/storage.rs:345]: is it safe to use native endianness? Do we risk to write with one endianness and then later read with another endianess (on the client)?

Comment (skejserjensen) [reply crates/modelardb_common/src/storage.rs:345]: Attempts have been made to ensure ModelarDB works on systems with different endianess, e.g., the [compression purposely uses little-endian](https://github.com/ModelarData/ModelarDB-RS/blob/84c886f07dbd470ff8a5803ca68dee3ea246fe03/crates/modelardb_compression/src/types.rs#L298) to ensure a specific endianess is used for compressed segments regardless of the system's endianess. Little-endiann was chosen as high performance CPUs such as [X86_64 and M-series](https://developer.apple.com/documentation/apple-silicon/porting-your-macos-apps-to-apple-silicon#Address-Architectural-Differences) uses little-endian. Unfortunately, GitHub Actions does not, as far as I am aware, [provide runners for any big-endian systems](https://github.com/actions/runner-images). Thus, ModelarDB has never been tested on anything but little-endian, so I am certain that there are issues we have not considered, e.g., Apache Arrow specifically states that it is [little-endian by default](https://arrow.apache.org/docs/format/Columnar.html#byte-order-endianness).

Regarding the use of native-endianness in the function executed by `unary()`, it was purposely used as [`unary()`](https://docs.rs/arrow/latest/arrow/array/struct.PrimitiveArray.html#method.unary) operates on [`ArrowPrimitiveType`](https://docs.rs/arrow/latest/arrow/datatypes/trait.ArrowPrimitiveType.html) which in this case is [`UInt64Type`](https://docs.rs/arrow/latest/arrow/datatypes/struct.UInt64Type.html) which corresponds to the native Rust type [`u64`](https://doc.rust-lang.org/nightly/std/primitive.u64.html) which is native-endian, e.g., see the documentation for [from_be()](https://doc.rust-lang.org/nightly/std/primitive.u64.html#method.from_be). However, according to the [documentation for Apache Parquet](https://parquet.apache.org/docs/file-format/data-pages/encodings/), it always stores integers as little-endian. So if I understand the process correctly, integers are stored in Apache Parquet as little-endian, read into and stored in Apache Arrow as little-endian, converted to native-endian when manipulated by `unary()` which is a [no-op for little-endian systems](https://doc.rust-lang.org/nightly/std/primitive.u64.html#method.from_le), and than written back to Apache Arrow as little-endian. Thus, the function executed by `unary()` must use native-endianess to be portable. However, there may certainly be something that I have overlooked or misunderstood, and as stated above, the code has only been tested on little-endian systems as I do not have access to systems with any other endianess.

File: crates/modelardb_common/src/storage.rs (hunk 1 above)
Comment (skejserjensen) [reply crates/modelardb_common/src/storage.rs:359]: See [this comment](https://github.com/ModelarData/ModelarDB-RS/pull/198#discussion_r1711403886).

**Review by chrthomsen — APPROVED** [review]

File: crates/modelardb_common/src/storage.rs [hunk 3]
```diff
@@ -330,6 +335,34 @@ pub async fn extract_azure_blob_storage_arguments(
...
+        columns[0] = Arc::new(signed_univariate_ids);
+
+        // unwrap() is safe as columns are constructs to match DISK_COMPRESSED_SCHEMA.
```
Comment (CGodiksen) [inline crates/modelardb_common/src/storage.rs:348]: Should this be `as columns is constructed`?

File: crates/modelardb_common/src/storage.rs [hunk 4]
```diff
@@ -330,6 +335,34 @@ pub async fn extract_azure_blob_storage_arguments(
...
+        *record_batch = RecordBatch::try_new(DISK_COMPRESSED_SCHEMA.0.clone(), columns).unwrap();
+    }
+}
+
+/// Reinterpret the bits used for univariate ids in `compressed_segments` to convert the column from
```
Comment (CGodiksen) [inline crates/modelardb_common/src/storage.rs:353]: Maybe make it clear that a new record batch is returned to avoid confusion with the above function that looks similar but instead converts the given record batch directly.

File: crates/modelardb_common/src/storage.rs (hunk 3 above)
Comment (CGodiksen) [reply crates/modelardb_common/src/storage.rs:348]: if this is changed here also change it in the function below.

**Review by CGodiksen — CHANGES_REQUESTED** [review]

File: crates/modelardb_common/src/storage.rs (hunk 3 above)
Comment (skejserjensen) [reply crates/modelardb_common/src/storage.rs:348]: Fixed.

File: crates/modelardb_common/src/storage.rs (hunk 4 above)
Comment (skejserjensen) [reply crates/modelardb_common/src/storage.rs:355]: Fixed.

**Review by CGodiksen — APPROVED** [review]
