### PR TITLE
Fix bug where an empty folder is created when opening a Delta table that does not exist

### LINKED ISSUE #386: Fix side effect in delta_table_from_path() in DataFolder
`delta_table_from_path()` uses `deltalake::ensure_table_uri()` before `deltalake::open_table_with_storage_options()` which creates an empty folder if the folder for the table does not already exist. When `deltalake::open_table_with_storage_options()` then returns an error (because the table does not exist), the empty folder is left over.

### PR DESCRIPTION
**Pull request by CGodiksen**
This PR closes https://github.com/ModelarData/ModelarDB-RS/issues/386 by fixing the side effect in `DataFolder::delta_table_from_path()` that caused an empty folder to be created even when the Delta table did not exist due to the use of `deltalake::ensure_table_uri()`. 

This has been fixed and since `DataFolder::delta_table_from_path()` now works better with tables that does not exist, `is_normal_table` and `is_time_series_table` have been updated to use the Delta table to check for the table type. This avoids a query of the metadata table and is very efficient on repeated calls due to the Delta table cache in DataFolder.

### CODE REVIEW

File: crates/modelardb_storage/src/data_folder/mod.rs [hunk 1]
```diff
@@ -762,7 +759,13 @@ impl DataFolder {
             Ok(delta_table.clone())
         } else {
             // If the table is not in the cache, open it and add it to the cache before returning.
-            let table_url = deltalake::ensure_table_uri(table_path)?;
+            let table_url =
+                deltalake::table::builder::parse_table_uri(table_path).map_err(|_error| {
```
Comment (skejserjensen) [inline crates/modelardb_storage/src/data_folder/mod.rs:764]: Unclear why this is manually mapped to an `InvalidArgument` instead of just using automatic wrapping by the question mark operator. If there is no implementation and/or conversion for the returned error type in `ModelarDbStorageError`, maybe implement it, if there is another reason why this is done manually, maybe add a comment to explain it.

**Review by skejserjensen — APPROVED** [review]

File: crates/modelardb_storage/src/data_folder/mod.rs (hunk 1 above)
Comment (CGodiksen) [reply crates/modelardb_storage/src/data_folder/mod.rs:764]: Added a comment that specifies that we change it since the error message from deltalake is very unclear. Mapping it to our own error makes the error message of a few DataFolder methods much cleaner.

**Review by chrthomsen — APPROVED** [review]
