### PR TITLE
Replace unwrap() with expect("why")

### LINKED ISSUE #249: Replace unwrap() with expect("why") or Result?
Currently a few `unwrap()`s are used in non-test code when an `Option` is returned that cannot be `None` and when a `Result` is returned that cannot be `Err`. By convention, the use of `unwrap()` is accommodated by a comment that documents why it is safe to use. However, to simplify debugging in the case an assumption that would make an `unwrap()` safe does not hold, maybe `expect()` should be used instead with information about which assumption did not hold as the argument. Although, if it is safe for the process to continue running despite the assumption being wrong, an `Result` or an `Option` should probably be returned to allow the system to recover from the error instead of simply terminating. Also if possible due to the use of `unwrap()` in test code, maybe enable the [optional Clippy lints](https://rust-lang.github.io/rust-clippy/master) that detect of `unwrap()` and `panic()`.

### PR DESCRIPTION
**Pull request by CGodiksen**
Closes #249 by replacing most uses of `unwrap()` with `expect("why should it not fail")`. Note that we still use `unwrap()` in tests. The message style in the expect messages is based on the [Rust style guide](https://doc.rust-lang.org/std/error/index.html#common-message-styles).

### CODE REVIEW

File: crates/modelardb_bulkloader/src/main.rs [hunk 1]
```diff
@@ -52,14 +52,22 @@ async fn main() -> Result<()> {
...
-    args.next().unwrap();
-
-    // unwrap() on args.next() is safe as args contains at least five elements.
-    let operation = args.next().unwrap();
-    let input_path = args.next().unwrap();
-    let output_path = args.next().unwrap();
-    let table_name = args.next().unwrap();
+    // Drop the path of the binary.
+    args.next()
+        .expect("args should contain at least five arguments.");
```
Comment (skejserjensen) [inline crates/modelardb_bulkloader/src/main.rs]: Instead of duplicating the string, maybe assign it to a `str` variable and pass it to each.

File: crates/modelardb_bulkloader/src/main.rs [hunk 2]
```diff
@@ -52,14 +52,22 @@ async fn main() -> Result<()> {
         print_usage_and_exit_with_error();
     }
 
-    // unwrap() is safe as the path of the binary is dropped.
```
Comment (skejserjensen) [inline crates/modelardb_bulkloader/src/main.rs]: @CGodiksen and @chrthomsen open question, should we keep all the `unwrap()` comments and just replace `unwrap()` with `expect()`. Since the `expect()` messages seem to inform the user about what went wrong, while the comments seem to inform the developer what invariance should prevent the `expect()` from ever being triggered both seem useful.

File: crates/modelardb_server/src/storage/types.rs [hunk 3]
```diff
@@ -60,63 +60,80 @@ impl MemoryPool {
...
         compressed_memory_in_bytes: usize,
     ) -> Self {
-        // unwrap() is safe as i64::MAX is 8192 PiB and the value is from ConfigurationManager.
         Self {
             wait_for_ingested_memory: Condvar::new(),
             remaining_ingested_memory_in_bytes: Mutex::new(
-                ingested_memory_in_bytes.try_into().unwrap(),
+                ingested_memory_in_bytes
+                    .try_into()
+                    .expect("ingested_memory_in_bytes should be less than 8192 PiB."),
```
Comment (skejserjensen) [inline crates/modelardb_server/src/storage/types.rs]: Maybe use a variable instead of repeating the same string.

File: crates/modelardb_server/src/storage/types.rs [hunk 4]
```diff
@@ -60,63 +60,80 @@ impl MemoryPool {
...
     }
 
     /// Change the amount of memory available for ingested data by `size_in_bytes`.
     pub(super) fn adjust_ingested_memory(&self, size_in_bytes: isize) {
-        // unwrap() is safe as lock() only returns an error if the mutex is poisoned.
-        *self.remaining_ingested_memory_in_bytes.lock().unwrap() += size_in_bytes;
+        *self
+            .remaining_ingested_memory_in_bytes
+            .lock()
+            .expect("Mutex should not be poisoned.") += size_in_bytes;
```
Comment (skejserjensen) [inline crates/modelardb_server/src/storage/types.rs]: Maybe use a variable or global constant instead of repeating the same string.

File: crates/modelardb_storage/src/query/sorted_join_exec.rs [hunk 5]
```diff
@@ -253,8 +253,10 @@ impl SortedJoinStream {
     /// rows and if not drop rows from the [`RecordBatches`](RecordBatch) that contain extra. This
     /// can occur as compressed segments are not transferred atomically to the remote data folder.
     fn set_batch_num_rows_to_smallest(&mut self) {
-        // unwrap() is safe as a record batch is read from each input before this method is called.
-        let first_batch_num_rows = self.batches[0].as_ref().unwrap().num_rows();
+        let first_batch_num_rows = self.batches[0]
+            .as_ref()
+            .expect("A record batch should be read from each input before this method is called.")
```
Comment (skejserjensen) [inline crates/modelardb_storage/src/query/sorted_join_exec.rs]: Maybe use a variable or a global constant instead of repeating the same string.

**Review by skejserjensen — CHANGES_REQUESTED** [review]

File: crates/modelardb_server/src/storage/types.rs (hunk 3 above)
Comment (CGodiksen) [reply crates/modelardb_server/src/storage/types.rs]: Fixed,

File: crates/modelardb_server/src/storage/types.rs (hunk 4 above)
Comment (CGodiksen) [reply crates/modelardb_server/src/storage/types.rs]: Fixed.
